# Generated by Django 4.1.3 on 2022-12-06 13:37

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_number_alter_room_sleepers_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                verbose_name="Nights range"
            ),
        ),
    ]
