# Generated by Django 4.1.3 on 2022-12-06 15:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_booking_date_range"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="sleepers_num",
            new_name="capacity",
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="Room name"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.PositiveIntegerField(unique=True, verbose_name="Room number"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Price per night",
            ),
        ),
    ]
